#!/bin/bash

if [ -z "$1" ]; then
	echo "Provide the file to replace the variables in as the first argument"
	exit 1
fi

if [ ! -f "$1" ]; then
	echo "$1 does not exist"
	exit 2
fi

envsubst "`printf '${%s} ' $(bash -c "compgen -A variable")`" < "$1" > "$1.tmp"
mv "$1.tmp" "$1"

